//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcaldia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Constancias
    {
        public int IdConstaniacia { get; set; }
        public string Inss { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Fechaconstancias { get; set; }
        [DisplayFormat(DataFormatString = @"{0:hh\:mm}")]
        public Nullable<System.TimeSpan> Horaconstancias { get; set; }
        public string ServicioMedico { get; set; }
        public string Especialidad { get; set; }
        public string Observaciones { get; set; }
        public string NumeroConstancia { get; set; }
        public byte[] Escaner { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
