//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcaldia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Asistencias = new HashSet<Asistencias>();
            this.Constancias = new HashSet<Constancias>();
            this.Deducciones = new HashSet<Deducciones>();
            this.Permisos = new HashSet<Permisos>();
            this.Subcidio = new HashSet<Subcidio>();
            this.Vacaciones1 = new HashSet<Vacaciones>();
        }
    
        public string Inss { get; set; }
        public string Cedula { get; set; }
        public string NombreCompleto { get; set; }
        public string EstadoCivil { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> FechaNacimiento { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string DatosLaborales { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> IdPlanilla { get; set; }
        public Nullable<int> IdDpt { get; set; }
        public string Hospital { get; set; }
        public string NivelAcademico { get; set; }
        public string Cargo { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public Nullable<double> Vacaciones { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Sexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencias> Asistencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constancias> Constancias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deducciones> Deducciones { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Planilla Planilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permisos> Permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subcidio> Subcidio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacaciones> Vacaciones1 { get; set; }
    }
}
