//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcaldia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlcaldiaEntities1 : DbContext
    {
        public AlcaldiaEntities1()
            : base("name=AlcaldiaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencias> Asistencias { get; set; }
        public virtual DbSet<Constancias> Constancias { get; set; }
        public virtual DbSet<Deducciones> Deducciones { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Planilla> Planilla { get; set; }
        public virtual DbSet<Subcidio> Subcidio { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoSubcidio> TipoSubcidio { get; set; }
        public virtual DbSet<Vacaciones> Vacaciones { get; set; }
    }
}
