
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Alcaldia.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Permisos
{

    public int IdPermisos { get; set; }

    public string Inss { get; set; }

    public Nullable<System.DateTime> Fechapermisos { get; set; }

    public Nullable<System.TimeSpan> Horapermisossalida { get; set; }

    public Nullable<System.TimeSpan> Horapermisosentrada { get; set; }

    public string Observaciones { get; set; }

    public Nullable<bool> Estado { get; set; }



    public virtual Empleado Empleado { get; set; }

}

}
